site_name: Network Monitoring
site_description: Network Monitoring documentation

site_author: "Alexander Sandoval"

site_url: "https://suga0828.github.io/network-monitoring/"

repo_name: "suga0828/network-monitoring"
repo_url: "https://github.com/suga0828/network-monitoring"

docs_dir: .

copyright: "@suga0828"

theme:
  favicon: assets/favicon.ico
  logo: assets/logo.png
  language: en
  name: simple-blog
  components:
    title: false

nav:
  - Home: index.md
  - Tutorials:
      - Install CentOS 9 Stream: tutorials/install-centos/README.md
      - Install LAMP Stack: tutorials/install-LAMP-stack/README.md
      - Install Zabbix: tutorials/install-zabbix/README.md
      - Install Zabbix Agent: tutorials/install-zabbix-agent-windows/README.md
      - Install Postfix: tutorials/install-postfix-gmail/README.md
      - Config Zabbix Agent Alert: tutorials/trigger-alert-zabbix-agent/README.md
      - Install SNMPv3: tutorials/install-config-SNMPv3/README.md

plugins:
  - search
  - same-dir
