site_name: Network Monitoring
site_description: Network Monitoring documentation

site_author: "Alexander Sandoval"

site_url: "https://suga0828.github.io/network-monitoring/"

repo_name: "suga0828/network-monitoring"
repo_url: "https://github.com/suga0828/network-monitoring"

docs_dir: .

copyright: Alexander Sandoval

theme:
  favicon: assets/favicon.ico
  logo: assets/logo.png
  language: en
  name: simple-blog
  components:
    title: false

nav:
  - Home: index.md
  - Tutorials:
      - tutorials/install-centos/README.md
      - tutorials/install-LAMP-stack/README.md
      - tutorials/install-zabbix/README.md
      - tutorials/install-zabbix-agent-windows/README.md
      - tutorials/install-postfix-gmail/README.md

plugins:
  - search
  - same-dir
